services:
  cudl-search-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epsilon-solr-api
    environment:
      SOLR_HOST: ${SOLR_HOST:-host.docker.internal}
      SOLR_PORT: ${SOLR_PORT:-8983}
      API_PORT: ${API_PORT:-80}
      NUM_WORKERS: 5
    ports:
      - ${API_PORT}:${API_PORT}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 512M
